[2024-07-11T07:26:37.974+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T07:26:37.991+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres manual__2024-07-11T07:10:19.817387+00:00 [queued]>
[2024-07-11T07:26:38.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres manual__2024-07-11T07:10:19.817387+00:00 [queued]>
[2024-07-11T07:26:38.014+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-11T07:26:38.024+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_postgres> on 2024-07-11 07:10:19.817387+00:00
[2024-07-11T07:26:38.033+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=655) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T07:26:38.034+0000] {standard_task_runner.py:63} INFO - Started process 657 to run task
[2024-07-11T07:26:38.035+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_data_to_postgres', 'manual__2024-07-11T07:10:19.817387+00:00', '--job-id', '985', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpokly5xau']
[2024-07-11T07:26:38.036+0000] {standard_task_runner.py:91} INFO - Job 985: Subtask load_data_to_postgres
[2024-07-11T07:26:38.077+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_data_to_postgres manual__2024-07-11T07:10:19.817387+00:00 [running]> on host aa283b53dd54
[2024-07-11T07:26:38.311+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T07:10:19.817387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T07:10:19.817387+00:00'
[2024-07-11T07:26:38.312+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T07:26:38.324+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-07-11T07:26:38.417+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-11T07:26:38.417+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T07:26:38.427+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_data_to_postgres, run_id=manual__2024-07-11T07:10:19.817387+00:00, execution_date=20240711T071019, start_date=20240711T072637, end_date=20240711T072638
[2024-07-11T07:26:38.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-11T07:26:38.489+0000] {taskinstance.py:3503} INFO - 4 downstream tasks scheduled from follow-on schedule check
[2024-07-11T07:26:38.490+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
