[2024-07-10T10:05:20.918+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T10:05:20.941+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.create_fact_table manual__2024-07-10T10:04:38.133311+00:00 [queued]>
[2024-07-10T10:05:20.947+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.create_fact_table manual__2024-07-10T10:04:38.133311+00:00 [queued]>
[2024-07-10T10:05:20.947+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-10T10:05:20.955+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): create_fact_table> on 2024-07-10 10:04:38.133311+00:00
[2024-07-10T10:05:20.963+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T10:05:20.964+0000] {standard_task_runner.py:63} INFO - Started process 151 to run task
[2024-07-10T10:05:20.965+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'create_fact_table', 'manual__2024-07-10T10:04:38.133311+00:00', '--job-id', '672', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmplkz_nsye']
[2024-07-10T10:05:20.968+0000] {standard_task_runner.py:91} INFO - Job 672: Subtask create_fact_table
[2024-07-10T10:05:21.071+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.create_fact_table manual__2024-07-10T10:04:38.133311+00:00 [running]> on host 514b016b59c3
[2024-07-10T10:05:21.259+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='create_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T10:04:38.133311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-10T10:04:38.133311+00:00'
[2024-07-10T10:05:21.261+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T10:05:21.270+0000] {python.py:237} INFO - Done. Returned value was:     SECURITY_ID  ...                                           PRICE_ID
0          ADBL  ...  ADBL_<bound method Timestamp.date of Timestamp...
1           AHL  ...  AHL_<bound method Timestamp.date of Timestamp(...
2          AHPC  ...  AHPC_<bound method Timestamp.date of Timestamp...
3         AKJCL  ...  AKJCL_<bound method Timestamp.date of Timestam...
4          AKPL  ...  AKPL_<bound method Timestamp.date of Timestamp...
..          ...  ...                                                ...
310        USHL  ...  USHL_<bound method Timestamp.date of Timestamp...
311        USLB  ...  USLB_<bound method Timestamp.date of Timestamp...
312        VLBS  ...  VLBS_<bound method Timestamp.date of Timestamp...
313       VLUCL  ...  VLUCL_<bound method Timestamp.date of Timestam...
314        WNLB  ...  WNLB_<bound method Timestamp.date of Timestamp...

[315 rows x 9 columns]
[2024-07-10T10:05:21.283+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T10:05:21.363+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=create_fact_table, run_id=manual__2024-07-10T10:04:38.133311+00:00, execution_date=20240710T100438, start_date=20240710T100520, end_date=20240710T100521
[2024-07-10T10:05:21.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-10T10:05:21.481+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T10:05:21.495+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
