[2024-07-10T04:38:15.638+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T04:38:15.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres manual__2024-07-10T04:37:45.734809+00:00 [queued]>
[2024-07-10T04:38:15.748+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres manual__2024-07-10T04:37:45.734809+00:00 [queued]>
[2024-07-10T04:38:15.748+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-10T04:38:15.758+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_postgres> on 2024-07-10 04:37:45.734809+00:00
[2024-07-10T04:38:15.771+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=250) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T04:38:15.772+0000] {standard_task_runner.py:63} INFO - Started process 252 to run task
[2024-07-10T04:38:15.774+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_data_to_postgres', 'manual__2024-07-10T04:37:45.734809+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpnltbgvc7']
[2024-07-10T04:38:15.780+0000] {standard_task_runner.py:91} INFO - Job 227: Subtask load_data_to_postgres
[2024-07-10T04:38:15.843+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_data_to_postgres manual__2024-07-10T04:37:45.734809+00:00 [running]> on host 72ddc95a1902
[2024-07-10T04:38:16.178+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T04:37:45.734809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-10T04:37:45.734809+00:00'
[2024-07-10T04:38:16.180+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T04:38:16.193+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-07-10T04:38:16.466+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-10T04:38:16.467+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T04:38:16.488+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_data_to_postgres, run_id=manual__2024-07-10T04:37:45.734809+00:00, execution_date=20240710T043745, start_date=20240710T043815, end_date=20240710T043816
[2024-07-10T04:38:16.548+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-10T04:38:16.574+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T04:38:16.575+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
