[2024-07-11T01:57:26.492+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T01:57:26.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres manual__2024-07-11T01:56:54.826866+00:00 [queued]>
[2024-07-11T01:57:26.536+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres manual__2024-07-11T01:56:54.826866+00:00 [queued]>
[2024-07-11T01:57:26.536+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-11T01:57:26.545+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_postgres> on 2024-07-11 01:56:54.826866+00:00
[2024-07-11T01:57:26.553+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T01:57:26.555+0000] {standard_task_runner.py:63} INFO - Started process 131 to run task
[2024-07-11T01:57:26.556+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_data_to_postgres', 'manual__2024-07-11T01:56:54.826866+00:00', '--job-id', '869', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp9hkc3t88']
[2024-07-11T01:57:26.565+0000] {standard_task_runner.py:91} INFO - Job 869: Subtask load_data_to_postgres
[2024-07-11T01:57:26.640+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_data_to_postgres manual__2024-07-11T01:56:54.826866+00:00 [running]> on host aa283b53dd54
[2024-07-11T01:57:26.938+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T01:56:54.826866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T01:56:54.826866+00:00'
[2024-07-11T01:57:26.939+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T01:57:26.949+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-07-11T01:57:27.052+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-11T01:57:27.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T01:57:27.064+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_data_to_postgres, run_id=manual__2024-07-11T01:56:54.826866+00:00, execution_date=20240711T015654, start_date=20240711T015726, end_date=20240711T015727
[2024-07-11T01:57:27.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-11T01:57:27.153+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T01:57:27.154+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
