[2024-06-26T09:40:39.928+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T09:40:39.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.upload_to_s3 manual__2024-06-26T09:40:12.900731+00:00 [queued]>
[2024-06-26T09:40:39.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.upload_to_s3 manual__2024-06-26T09:40:12.900731+00:00 [queued]>
[2024-06-26T09:40:39.948+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-26T09:40:39.956+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_s3> on 2024-06-26 09:40:12.900731+00:00
[2024-06-26T09:40:39.964+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T09:40:39.965+0000] {standard_task_runner.py:63} INFO - Started process 88 to run task
[2024-06-26T09:40:39.966+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'upload_to_s3', 'manual__2024-06-26T09:40:12.900731+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp9r4d0gpl']
[2024-06-26T09:40:39.968+0000] {standard_task_runner.py:91} INFO - Job 167: Subtask upload_to_s3
[2024-06-26T09:40:40.035+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.upload_to_s3 manual__2024-06-26T09:40:12.900731+00:00 [running]> on host f3f48f0457b9
[2024-06-26T09:40:40.249+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T09:40:12.900731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T09:40:12.900731+00:00'
[2024-06-26T09:40:40.250+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T09:40:40.265+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-06-26T09:40:40.265+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2024-06-26T09:40:40.265+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2024-06-26T09:40:42.401+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-26T09:40:42.403+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T09:40:42.433+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=upload_to_s3, run_id=manual__2024-06-26T09:40:12.900731+00:00, execution_date=20240626T094012, start_date=20240626T094039, end_date=20240626T094042
[2024-06-26T09:40:42.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T09:40:42.513+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T09:40:42.514+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
