[2024-07-09T06:44:21.092+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T06:44:21.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.create_security_dimension scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-09T06:44:21.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.create_security_dimension scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-07-09T06:44:21.117+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-07-09T06:44:21.126+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): create_security_dimension> on 2024-06-25 00:00:00+00:00
[2024-07-09T06:44:21.140+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=47) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-09T06:44:21.151+0000] {standard_task_runner.py:63} INFO - Started process 54 to run task
[2024-07-09T06:44:21.155+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'create_security_dimension', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp7cyuzoak']
[2024-07-09T06:44:21.161+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask create_security_dimension
[2024-07-09T06:44:21.270+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.create_security_dimension scheduled__2024-06-25T00:00:00+00:00 [running]> on host e3bf5389da5f
[2024-07-09T06:44:21.603+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='create_security_dimension' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-07-09T06:44:21.606+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T06:44:21.609+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T06:44:21.611+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 61, in create_security_dimension
    security_dimension = df[['SECURITY_ID', 'SYMBOL', 'SECURITY_NAME', 'MARKET_CAPITALIZATION', 'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW']].drop_duplicates().copy()
                         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['SECURITY_ID', 'SYMBOL', 'SECURITY_NAME', 'MARKET_CAPITALIZATION',\n       'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW'],\n      dtype='object')] are in the [columns]"
[2024-07-09T06:44:21.640+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=create_security_dimension, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240709T064421, end_date=20240709T064421
[2024-07-09T06:44:21.665+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task create_security_dimension ("None of [Index(['SECURITY_ID', 'SYMBOL', 'SECURITY_NAME', 'MARKET_CAPITALIZATION',\n       'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW'],\n      dtype='object')] are in the [columns]"; 54)
[2024-07-09T06:44:21.705+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-09T06:44:21.752+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T06:44:21.754+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
